### ISSUE TITLE
DB query returns no results

### ISSUE THREAD

**Issue by gebeer** [BitPoet/JsonNativeField#3]
Thank you for putting this together. I used your DB getMatchQuery code in my module that stores field values as json.
The queries didn't return anything until I removed ```.value``` from the ```$path``` variable around https://github.com/BitPoet/JsonNativeField/blob/96bf1d92121c806b329ea6609b3db30de0341b6f/FieldtypeJsonNative.module#L48
Just wondering why you have it there. Was there a change in JSON_SEARCH specs?

**Comment by BitPoet** [comment]
Hi, only now saw your issue report. No, the json_search specs haven't changed, the .value is due to how my module serializes its data. Every value in my field type is encapsulated in a Json_Value object with a "type" and "value" property. This isn't really necessary now, but it might come in handy in the future (if MySQL's JSON features get extended) to make searching for non-text data types (like dates e.g.) more powerful. I was speculating on a few (not yet present) additions to json_search when I implemented it this way.

**Comment by gebeer** [comment]
Thanks for clarifying!
